### PR TITLE
Add django-rq

### PR DESCRIPTION
**Pull request by sysmso**
django-rq is missing and cause crash at start

### CODE REVIEW

**Comment by vsoch** [comment]
It’s in the requirements.txt, did you rebuild using a cache? https://github.com/singularityhub/sregistry/blob/master/requirements.txt

**Comment by sysmso** [comment]
Strange, it's in my requirements.txt too, but wasn't installed in the image from dockerhub...

**Comment by vsoch** [comment]
haha, no not strange, more just a brain fart on my part! The deploy step failed and I didn't catch it.

image

Give me a few minutes and I'll fix it up.

**Comment by vsoch** [comment]
Okay we're deployed! Would you care to test (latest, by commit, or version 1.1.0) see https://hub.docker.com/r/vanessa/sregistry/tags. If this resolves the issue, then we can close this here. And apologies again for missing this.

**Comment by sysmso** [comment]
Seems ok, we can close !

**Pull request closed without merging**
