### PR TITLE
Documentation of the Ansible role

### PR DESCRIPTION
**Pull request by serlophug**
I created the documentation to use the Ansible role.  I did not test it using Github pages because I do not know how to do it. Feel free to modify anything :)

### CODE REVIEW

**Comment by vsoch** [comment]
Beautiful! Taking a look now.

**Comment by vsoch** [comment]
Ok - I did a small re-organization so that the Ansible docs are under a new section for other deployments (so it stands out a little better!) and minor tweaks of the page.

**Comment by serlophug** [comment]
Perfect!

**Comment by vsoch** [comment]
Are you on Twitter? I'd like to Tweet it to thank you :)

**Comment by serlophug** [comment]
Yes, I just joined on Twitter :)

**Pull request merged**
