### PR TITLE
updating sregistry to version 0.0.74

### PR DESCRIPTION
**Pull request by vsoch**
This PR will update the sregistry version, and specify installation of the registry module to ensure requests_toolbelt and the timestamp generation functions are installed. Notably, we in the api and url functions we move the timestamp generation function into the registry module as they are no longer in a global auth.

### CODE REVIEW

**Comment by vsoch** [comment]
This will close #106 - @Trophime would you like to take a look? Are you ok with updating the version and still being specific, so we can still be sure about future changes? I've tested locally as well. When you approve we can merge into master.

**Comment by Trophime** [comment]
Before testing the PR, I've tried to move from http to https as:
`singularity pull shub://localhost/...` seems to requires https.

I'm having some troubles when trying to get https working (with twitter oauth so far)
Do we need a valid certificate  (I mean not self signed) for https to work?

**Comment by vsoch** [comment]
If you need regular http to work, then you should check the `DOMAIN_NAME` in settings (see here https://github.com/singularityhub/sregistry/blob/master/shub/settings/config.py#L42), along with making sure you are using the correct docker-compose and nginx.conf (both in this folder https://github.com/singularityhub/sregistry/tree/master/https) that expose port 443. For twitter, (and most oauth) the callback URL is also really important! So if there is a difference it can reject. If the error is on the redirect, then sometimes you can just refresh and it will be logged in anyway. :)

**Comment by Trophime** [comment]
As I have a trouble to get a certificate, I revert to http.
So locally everything works smoothly ;)
However on a remote machine I've tried to pull an image using `sregistry pull salome/8.4.0:buster`:
```
[client|registry] [database|sqlite:////home/LNCMI-G/trophime/.singularity/sregistry.db]
Progress |===========================|-------|  79.0% 
ERROR Return Code 255: ERROR  : Failed to mount squashfs image in (read only): Invalid argument
ABORT  : Retval = 255

WARNING Inspect command not supported, metadata not included.
[container][new] salome/8.4.0:buster
Success! /home/LNCMI-G/trophime/singularity_images/salome-8.4.0:buster.simg
```
and trying to run the container fails:
```
singularity shell /home/LNCMI-G/trophime/singularity_images/salome
ERROR  : No valid /bin/sh in container
ABORT  : Retval = 255
```

**Comment by vsoch** [comment]
If you are testing on a remote machine, can you share with me the url so I can reproduce? and what sregistry version you are using would be helpful too.

**Comment by Trophime** [comment]
my sregistry is installed on calcul18.lcmi.local and I use singularity 2.4.4-1 and sregistry-cli 0.0.74 on the remote machine. For giving you access to the sregistry I would need your IP to open appropriate port and you have to connect with twitter... and send you back the IP of calcul18

**Comment by Trophime** [comment]
if there a limit when downloading with http? 
because it seems to work for "small" images (eg `1008M images/hifimagnet/latestbuster.simg`)
but not for `1.5G images/ensight/10.2.2mso4sc.simg`

**Comment by vsoch** [comment]
ah that might be it! The limit is set by the nginx header, and it looks like we might have missed updating one (here) https://github.com/singularityhub/sregistry/blob/master/https/nginx.conf.https#L36 for the https. It would be good to try changing that, restarting, and see if it fixes. What seems curious is that it tries to do something before reaching 100% and then has an invalid argument issued. So it may not be the header.

**Comment by Trophime** [comment]
but we have for http in `nginx.conf`:
```
  client_max_body_size 8000M;
  client_body_buffer_size 8000M;
```
these values exceed limits set for https no?

**Comment by vsoch** [comment]
yes but if you are using https it will use the https server block I think.

**Comment by Trophime** [comment]
I've setup everything for using http not https at least that what I think
How can I be sure?

**Comment by Trophime** [comment]
Actually, there is no https block defined.
and https port is not open!

**Comment by vsoch** [comment]
Haha, that might be an issue :) See if you can fix that up and try again!

**Comment by Trophime** [comment]
ok I'll give a trial..
I still have a question: can I use a self signed certificate?

**Comment by vsoch** [comment]
If the client allows and the server is configured correctly, I don't see why not. I'm by no means an expert on this though. Generally self signed is good for testing, but I'd advocate for setting up a proper one with lets encrypt. I have done this a few times and my method isn't likely the best, but it works so I'd be glad to help you if needed. I think I documented most of it in the setup for sregistry, so check that first!

**Comment by Trophime** [comment]
I've already did but it seems that I reach some limit of "Lets encrypt" because of my actual domain name "cnrs.fr" ... too bad

**Comment by vsoch** [comment]
I don't think the domain name is issue, I think you need something open (that isn't reachable) to send the tests. This issue seems similar https://community.letsencrypt.org/t/solved-cant-renew-ssl-certificate/55454/16 Domain names have huge variance in terms of extensions, so I don't see how they could limit them. Is there documentation you know of, or more details about your error?

**Comment by Trophime** [comment]
Changing this in `nginx.conf` fix my problem with large file:
```
  location / {
    include /etc/nginx/uwsgi_params.par;
    uwsgi_pass uwsgi:3031;
    uwsgi_max_temp_file_size 10024m;
  }
```

**Comment by vsoch** [comment]
oh this is great news! I didn't even know about that field. Do you want to PR to change it in nginx.conf for the registry (for both http and https?)

**Comment by vsoch** [comment]
@Trophime we got a little distracted with the https :) I've added the tweaks to the nginx.conf to set the max temporary file size - are you able to give the A-OK now on this pull request for merge? It's holding up the other ones!

**Comment by Trophime** [comment]
If we except the pb with https, everything is fine.
You can merge the pull request.
Thanks

**Comment by vsoch** [comment]
Awesome thanks!

**Pull request merged**
