### PR TITLE
removing controls_scripts reference

### PR DESCRIPTION
**Pull request by vsoch**
This is a PR to address bug fixes for @victorsndvg

### CODE REVIEW

**Comment by victorsndvg** [comment]
@vsoch , this seems to be a similar issue.

When I click on a collection I get the following error:

```
uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "./shub/apps/main/views/collections.py", line 168, in view_collection
uwsgi_1   |     return render(request, 'collections/view_collection.html', context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
uwsgi_1   |     content = loader.render_to_string(template_name, context, request, using=using)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
uwsgi_1   |     return template.render(context, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 68, in render
uwsgi_1   |     reraise(exc, self.backend)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 89, in reraise
uwsgi_1   |     six.reraise(exc.__class__, new, sys.exc_info()[2])
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
uwsgi_1   |     raise value.with_traceback(tb)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
uwsgi_1   |     return self.template.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 207, in render
uwsgi_1   |     return self._render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
uwsgi_1   |     return self.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
uwsgi_1   |     return compiled_parent._render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
uwsgi_1   |     return self.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
uwsgi_1   |     result = block.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
uwsgi_1   |     result = block.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
uwsgi_1   |     return nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 216, in render
uwsgi_1   |     nodelist.append(node.render_annotated(context))
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
uwsgi_1   |     return nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 204, in render
uwsgi_1   |     template = context.template.engine.get_template(template_name)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/engine.py", line 162, in get_template
uwsgi_1   |     template, origin = self.find_template(template_name)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/engine.py", line 148, in find_template
uwsgi_1   |     raise TemplateDoesNotExist(name, tried=tried)
uwsgi_1   | django.template.exceptions.TemplateDoesNotExist: globus/_container_details.html
```

**Comment by vsoch** [comment]
The template is there:

```bash
ls shub/plugins/globus/templates/globus/
_container_details.html  _transfer_endpoints.html  transfer.html
```
Do you have / don't have the globus plugin?

**Comment by victorsndvg** [comment]
I installed all requirements to have it working with globus, but I had disabled the `globus` plugin (its not configured  yet). After enabling the plugin it works.

I have one more issue. When I try to pull a public image with singularity it is not able to get the manifest. The error shown from the sregistry logs is:

```
uwsgi_1   | Internal Server Error: /api/container/mso4sc/example:latest
uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
uwsgi_1   |     return view_func(*args, **kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
uwsgi_1   |     return self.dispatch(request, *args, **kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
uwsgi_1   |     response = self.handle_exception(exc)
uwsgi_1   |   File "./shub/apps/logs/mixins.py", line 82, in handle_exception
uwsgi_1   |     response = super(BaseLoggingMixin, self).handle_exception(exc)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
uwsgi_1   |     self.raise_uncaught_exception(exc)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
uwsgi_1   |     response = handler(request, *args, **kwargs)
uwsgi_1   |   File "./shub/apps/api/urls/containers.py", line 153, in get
uwsgi_1   |     return _container_get(request, container, name, tag)
uwsgi_1   |   File "./shub/apps/api/urls/containers.py", line 180, in _container_get
uwsgi_1   |     return Response(serializer.data)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 560, in data
uwsgi_1   |     ret = super(Serializer, self).data
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 262, in data
uwsgi_1   |     self._data = self.to_representation(self.instance)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 527, in to_representation
uwsgi_1   |     ret[field.field_name] = field.to_representation(attribute)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/fields.py", line 1855, in to_representation
uwsgi_1   |     return method(value)
uwsgi_1   |   File "./shub/apps/api/urls/containers.py", line 65, in get_download_url
nginx_1   | 10.118.68.11 - - [23/May/2018:14:13:20 +0000] "GET /api/container/mso4sc/example:latest HTTP/1.1" 500 850 "-" "Python-urllib/2.6" "-"
uwsgi_1   |     return "%s%s" %(DOMAIN_NAME,url)
uwsgi_1   | NameError: name 'DOMAIN_NAME' is not defined
```

**Comment by victorsndvg** [comment]
I think the previous one can be fixed replacing `DOMAIN_NAME` by `settings.DOMAIN_NAME`.

After fixing this I got a new one:

```
uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
uwsgi_1   |     return view_func(*args, **kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
uwsgi_1   |     return self.dispatch(request, *args, **kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 485, in dispatch
uwsgi_1   |     self.response = self.finalize_response(request, response, *args, **kwargs)
uwsgi_1   |   File "./shub/apps/logs/mixins.py", line 109, in finalize_response
uwsgi_1   |     self.request.log.save()
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 806, in save
uwsgi_1   |     force_update=force_update, update_fields=update_fields)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 831, in save_base
uwsgi_1   |     update_fields=update_fields,
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in send
uwsgi_1   |     for receiver in self._live_receivers(sender)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
uwsgi_1   |     for receiver in self._live_receivers(sender)
uwsgi_1   |   File "./shub/apps/logs/models.py", line 67, in finalize_request
uwsgi_1   |     from shub.apps.logs.utils import get_request_collection
uwsgi_1   |   File "./shub/apps/logs/utils.py", line 24, in <module>
uwsgi_1   |     from registry.utils import read_json
uwsgi_1   | ImportError: No module named 'registry'
```

**Comment by victorsndvg** [comment]
Perfect! Thanks for your quick responses!!

**Comment by victorsndvg** [comment]
Working fine for me. Users can pull/push, create/manage teams, etc.

This check means that everything work as before. No news yet about globus. Now that sregistry is upgraded i can use it (with https) to test globus

**Comment by vsoch** [comment]
Great! Thanks for the review. Merging!

**Pull request merged**
