### PR TITLE
Adding keystore plugin

### PR DESCRIPTION
**Pull request by vsoch**
This is a first round of changes to test adding a [standard keystore](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00) to Singularity Registry Server to address #203. Specifically, to test you will need to:

 - follow instructions in the [plugin docs page](https://github.com/singularityhub/sregistry/tree/test/key-server/docs/_docs/plugins/pgp) to build the container with dependency pgpdump, and then make sure plugin "pgp" is not commented out for PLUGINS_ENABLED in settings/config.py
 - start the server as you normally would with `docker-compose up -d`
 - follow the getting started section also in the plugin docs to test creating a key, push, search, and pull.

:point_right: https://github.com/singularityhub/sregistry/tree/test/key-server/docs/_docs/plugins/pgp

This should provide the basic functionality - @asmi10 and @al3x609 would you care to test, since you requested this functionality? If anything is missing we can discuss and figure out how to add it.

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by asmi10** [comment]
Hi vsoch,

Thanks a lot for providing keystore function!
I was just trying it out after enabling pgp plugin, but I couldn't see any pks tab in sregistry web page. Also it seems push function only works with TLS, so I tried https but found below error. I am using using singularity version 3.4.1 master branch.

uwsgi_1 | Not Found: /pks/add/ │/sregistrytest.hpc.caas.intel.com 248A205C1795F62CF6177C774438D434EDF9F541
uwsgi_1 | [pid: 36|app: 0|req: 1/19] 10.216.137.221 () {38 vars in│ERROR: push failed: key server did not accept PGP key: 404 Not Found
1155 bytes} [Mon Oct 7 14:05:40 2019] GET /pks/add/ => generated 652 │musxtestvm006:~ # /infrastructure/sing/bin/singularity key push --url https:/
bytes in 916 msecs (HTTP/1.1 404) 3 headers in 116 bytes (1 switches on│/sregistrytest.hpc.caas.intel.com 248A205C1795F62CF6177C774438D434EDF9F541
core 1) │ERROR: push failed: key server did not accept PGP key: 404 Not Found
 1155 bytes} [Mon Oct  7 14:05:40 2019] GET /pks/add/ => generated 652 │musxtestvm006:~ # /infrastructure/sing/bin/singularity key push --url https:/
bytes in 916 msecs (HTTP/1.1 404) 3 headers in 116 bytes (1 switches on│/sregistrytest.hpc.caas.intel.com 248A205C1795F62CF6177C774438D434EDF9F541
 core 1)                                                               │ERROR:   push failed: key server did not accept PGP key: 404 Not Found

**Comment by vsoch** [comment]
Please read the description carefully - I linked you to full instructions to build the container with the plugin enabled, and enable it in your settings. if you don't do that, the endpoints won't be found, as you've shown.

**Comment by vsoch** [comment]
The push will work fine without TLS. Note that the error (for all of the above is 404, which means not found):

```
ERROR: push failed: key server did not accept PGP key: 404 Not Found
```
because you need to enable the plugin, and restart your containers.

**Comment by asmi10** [comment]
Yes, I enabled the plugin. Below is my config.py content
PLUGINS_ENABLED = [                                                                                                  │
    'pgp',                                                                                                           │
    'ldap_auth'                                                                                                      │
#    'google_build'                                                                                                  │
#    'pam_auth',                                                                                                     │
#    'globus',                                                                                                       │
#    'saml_auth'                                                                                                     │
]                    

This one is uwsgi container
:/infrastructure/key-server/sregistry # docker exec 104f23a9b7b0 pip freeze | grep -i pgp               │
pgpdump==1.5

**Comment by vsoch** [comment]
And you restarted the containers?

**Comment by asmi10** [comment]
yes, multiple times.

Below is the error if I use http instead of https
│musxtestvm006:~ # /infrastructure/sing/bin/singularity key push --u
│rl http://hpc-sregistry.intel.com 248A205C1795F62CF6177C774438D434E
│DF9F541
│ERROR:   push failed: TLS required when auth token provided

**Comment by vsoch** [comment]
So let's step back - the errors about not having the pks endpoint - is this resolved and you didn't tell me?

**Comment by asmi10** [comment]
pks endpoint is not resolved yet.

**Comment by vsoch** [comment]
If there is no pks endpoint, how are you trying to test a step that requires it?

**Comment by vsoch** [comment]
You are also correct that https is required when you aren't using localhost, this is set by sylabs. The error message you see is [here](https://github.com/sylabs/scs-key-client/blob/76c1f92aa198ed6259be2906c36758f3e6b5ae4a/client/client.go#L25) and it's triggered [here](https://github.com/sylabs/scs-key-client/blob/76c1f92aa198ed6259be2906c36758f3e6b5ae4a/client/client.go#L112). It's generally best practice to deploy with https - and even dangerous to not, so I would recommend this regardless.

**Comment by asmi10** [comment]
yes, testing should be performed later. I was just trying it out to check endpoint it is hitting in uwsgi & nginx logs;)
First I should see pks endpoint.

**Comment by vsoch** [comment]
I also can't reproduce your error - I removed all previous containers.

```bash
docker-compose stop
docker-compose rm
```
Rebuilt with the plugin enabled.

```
$ docker build --build-arg ENABLE_PGP=true -t quay.io/vanessa/sregistry .
```

Brought up the containers:

```
docker-compose up -d
```

And then shelled into uwsgi, and I can see the endpoints with pks:

```
# python manage.py show_urls | grep pks
/pks/add/	shub.plugins.pgp.views.add	add
/pks/lookup/	shub.plugins.pgp.views.lookup	lookup
```

I think it's very likely that you haven't restarted/updated the container, it's not logical that the urls aren't there.

**Comment by asmi10** [comment]
I can see them inside the container. Should I be seeing any tab in website?

# python manage.py show_urls | grep pks                                          │rl http://hpc-sregistry.intel.com 248A205C1795F62CF6177C774438D434E
/pks/add/       shub.plugins.pgp.views.add      add                              │DF9F541
/pks/lookup/    shub.plugins.pgp.views.lookup   lookup

**Comment by vsoch** [comment]
Great - you have the pks endpoints!

There are no urls that you can put into the browser - they are communicated with from the command line. And yes, you'll need https.

And just for the future - if you put code in ```these marks``` it will render (look at the raw text here to see what I mean). Otherwise it renders as markdown and looks broken.

**Comment by vsoch** [comment]
Based on the limits of what Sylabs has implemented in the client that I linked previously, to test this you will either need https on your server, or to run locally (and use localhost).

**Comment by vsoch** [comment]
I'll add a note to the documentation about this.

**Comment by asmi10** [comment]
musxtestvm006:~ # /infrastructure/sing/bin/singularity key push --url https://sregistrytest.hpc.caas.com 248A205C1795F62CF6177C774438D434EDF9F541
ERROR:   push failed: key server did not accept PGP key: 404 Not Found

below are uwsgi logs, it is showing /pks/add not found here.
uwsgi_1      | [pid: 42|app: 0|req: 22/29] 10.216.137.221 () {38 vars in 1121 bytes} [Mon Oct  7 14:50:11 2019] POST /pks/add => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 114 bytes (1 switches on core 1)
uwsgi_1      | Not Found: /pks/add/
uwsgi_1      | [pid: 37|app: 0|req: 1/30] 10.216.137.221 () {38 vars in 1155 bytes} [Mon Oct  7 14:50:12 2019] GET /pks/add/ => generated 652 bytes in 1080 msecs (HTTP/1.1 404) 3 headers in 116 bytes (1 switches on core 0)

**Comment by vsoch** [comment]
That's not what I'm seeing - I'm seeing a 301 redirect, and then the trailing slash isn't found.  Is there some special setup for your server with respect to a proxy or similar?

**Comment by vsoch** [comment]
You don't see any errors about `APPEND_SLASH` in your uwsgi logs?

**Comment by vsoch** [comment]
Ah! I think I just figured it out :) Will push in a second!

**Comment by vsoch** [comment]
@asmi10 please test now! The hint about the slash directed me to look at the urls, and I saw this:

```
urlpatterns = [
    url(r"^add?/$", views.add, name="add"),
    url(r"^lookup?/$", views.lookup, name="lookup"),
]
```
which should have been this!

```
urlpatterns = [
    url(r"^add/?$", views.add, name="add"),
    url(r"^lookup/?$", views.lookup, name="lookup"),
]
```
And this was my mistake - I added the optional question marks to the regular expressions at the end and forgot to check that it still worked. I think this should resolve your issue (just worked for me!)

**Comment by vsoch** [comment]
hey @asmi10 did you test? I'd like to release this soon!

**Comment by vsoch** [comment]
I'm happy with the changes and I'd like to release, so I'm going to merge. If you have further issues, please open them in separate issues. Thanks again @asmi10 !

**Pull request merged**
