### PR TITLE
Fix/messages

### PR DESCRIPTION
**Pull request by vsoch**
@victorsndvg does this ok to resolve the remaining issues?

### CODE REVIEW

**Comment by victorsndvg** [comment]
mmmm

Hi @vsoch, it seems that there is no `request` in some scopes. Maybe it has to be passed as an argument to some functions? or maybe I'm missing something?

Look at this lines:

https://github.com/singularityhub/sregistry/blob/e03a0b7ea85ec6d8639e3b5241927d826f70d5f7/shub/apps/users/views/teams.py#L224
https://github.com/singularityhub/sregistry/blob/e03a0b7ea85ec6d8639e3b5241927d826f70d5f7/shub/apps/users/views/teams.py#L240
https://github.com/singularityhub/sregistry/blob/e03a0b7ea85ec6d8639e3b5241927d826f70d5f7/shub/apps/users/views/teams.py#L243

**Comment by vsoch** [comment]
Ah, this is because the first "fix" to add the request was wrong to begin with! Those underscore (private) functions don't return directly to views, and the messages being there was legacy from when they returned json response. The messages shouldn't be there because they don't return to a view, and requests shouldn't be defined / used in the functions at all.

**Comment by victorsndvg** [comment]
Perfect, working! :+1:

**Comment by vsoch** [comment]
Awesome!

**Pull request merged**
