### PR TITLE
[WIP] Adding start to PAM plugin

### PR DESCRIPTION
**Pull request by vsoch**
This is currently not working, but I'm putting here so it's easy to see changes. See here https://github.com/cnobile2012/django-pam/issues/8 for the issues that I'm having.

### CODE REVIEW

**Comment by vsoch** [comment]
@sgabenov the pull request is ready for you to test, first clone the entire branch here:

```bash
git clone -b add/pam https://www.github.com/singularityhub/sregistry
```
And then follow the instructions in the docs (I've rendered them for you here) to enable and use PAM. Let me know how it goes! Please test:

 - logging in
 - pushing / pulling images
 - adding a new user and restarting the container

When all is good, we can merge the PR to make the docs and changes live on master.
[pam-authentication.pdf](https://github.com/singularityhub/sregistry/files/3019085/pam-authentication.pdf)

**Comment by vsoch** [comment]
ping @sgabenov have you had a chance to test?

**Comment by sgabenov** [comment]
Sorry for a long reply. For me looks good!

**Comment by vsoch** [comment]
ok thanks! Merging.

**Pull request merged**
