### PR TITLE
Correct link to settings/config.py

### PR DESCRIPTION
**Pull request by jbd**
I don't know if there is a "clean" way to build links between github.io and a github.com repository, so I used the full URI.

### CODE REVIEW

**Comment by jbd** [comment]
In fact, most of the relative links in the .md generate a 404. Mayve you'd like to handle it in a certain way ?

**Comment by vsoch** [comment]
You should be reading it in the online interface and not in the markdown files. Eg start at singularity hub.github.io/sregistry. A lot of these typos are likely correct for that rendering, let me know if this is the case.

**Comment by jbd** [comment]
I'm reading the documentation from https://singularityhub.github.io/sregistry/install

**Comment by vsoch** [comment]
Ah good catch! Yes the approach I think is most sound is to have the full path link to the file.

**Comment by vsoch** [comment]
Thanks for the fix!

**Comment by vsoch** [comment]
Also, if you are interested, the Globus integration is under review #113 and definitely needs reviewers! @victorsndvg is on the queue but I think he's very busy.

**Comment by victorsndvg** [comment]
Yep @vsoch , I'm very busy ... but excited by upcoming tests with globus! I will report as soon as possible ;)

**Pull request merged**
