### PR TITLE
Main

### PR DESCRIPTION
**Pull request by kkaftan**

### CODE REVIEW

**Comment by kkaftan** [comment]
sorry was mistake, meant to push in my own forked repo

**Comment by vsoch** [comment]
Any reason you can't contribute the recipe here?

**Comment by vsoch** [comment]
Or we could make a modular repo for the deployment alongside it.

**Comment by vsoch** [comment]
And if you don't have the bandwidth, I can offer to help!

**Comment by kkaftan** [comment]
There is no particular reason not to share. @hashkeks and I were testing the deployment possibilities with k8s and how it works. So what I tried to push is an unrefined version of our project. We would like to improve it, test it further and provide documentation before make publicly available. As it just a side project it may take some time, but we would be glad to come back to you, when we think its ready. :+1:

**Comment by vsoch** [comment]
Sounds good!

**Pull request closed without merging**
