### PR TITLE
fixing template error and adding JsonResponse import

### LINKED ISSUE #130: Make owner button broken
Hi @vsoch ,

I was trying to add new owners to a team but it does not work.

I think there is bug here (is not callink `make_owner` button):
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/templates/teams/team_details.html#L220

If I replace `add_owner` by `make_owner` it adds an user to the list of owners as expected, but the on the server side I get the following error:
```
uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1   |     return view_func(request, *args, **kwargs)
uwsgi_1   |   File "./shub/apps/users/views/teams.py", line 303, in add_owner
uwsgi_1   |     return JsonResponse({"message":message})
uwsgi_1   | NameError: name 'JsonResponse' is not defined
```

### PR DESCRIPTION
**Pull request by vsoch**
This PR will close #130

### CODE REVIEW

**Comment by victorsndvg** [comment]
A new one with remove owner:

```uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1   |     return view_func(request, *args, **kwargs)
uwsgi_1   |   File "./shub/apps/users/views/teams.py", line 283, in remove_owner
uwsgi_1   |     team = _remove_owner(team, user)
```

**Comment by vsoch** [comment]
What's the error?

**Comment by victorsndvg** [comment]
`make owner` button is working. `remove owner` button returns this error in the server log

**Comment by vsoch** [comment]
Is there no error line after what you posted? It looks like only part of the traceback.

**Comment by vsoch** [comment]
That's what I'm looking for! Thanks.

**Comment by vsoch** [comment]
Let me know if it's working! I made the fix.

**Comment by vsoch** [comment]
Merging! Thanks as always @victorsndvg  :)

**Pull request merged**
