### PR TITLE
Add Globus

### PR DESCRIPTION
**Pull request by vsoch**

### CODE REVIEW

**Comment by vsoch** [comment]
We are ready for testing! 

The docs for testing are here --> https://github.com/singularityhub/sregistry/blob/add/globus/docs/pages/plugins/globus/README.md

You can't actually see the pictures there, so you can either run the jekyll server locally, e.g.:

```
git clone -b add/globus https://github.com/singularityhub/sregistry
cd sregistry/docs
jekyll serve
# browse to http://127.0.0.1:4000/sregistry/plugin-globus
```
or I'm attaching the PDF docs of the same here.

[sregistry-globus.pdf](https://github.com/singularityhub/sregistry/files/1948573/sregistry-globus.pdf)

**Comment by vsoch** [comment]
ping @victorsndvg for round 1 testing!

**Comment by vsoch** [comment]
hey @victorsndvg any updates on reviewing here? 18 days is a long time... lol

**Comment by victorsndvg** [comment]
a long time???? is too short! haha

sorry for the huge delay.

I've already started the testing process.  Now I've to iterate with the person in charge of the data node here to be able to interact with it (is not fully in production).  

I expect to have results this week.

**Comment by vsoch** [comment]
haha ok, thanks @victorsndvg !

**Comment by victorsndvg** [comment]
No results yet ... to busy :sweat: 

I promise you, next week I will report my results.

Sorry

**Comment by vsoch** [comment]
it's ok @victorsndvg hang in there!! Your review will be great because you put good time into them, and I'm definitely ok with waiting :)

**Comment by vsoch** [comment]
This is too long @victorsndvg, it's been a month! I'm merging, and if you have issues you can open them.

**Comment by victorsndvg** [comment]
Yes, this is totally understandable. My delay is unacceptable ...

Sorry again.

Anyway, I will try to provide feedback

**Comment by victorsndvg** [comment]
Hi @vsoch ,

I re-deploy the new version and something broke the previous one. All seems to work (teams, user, etc.) except collections and containers. When I click on them I get a "bee bop". I also cannot pull containers with singularity, I get the following error:

```
Error getting image manifest using url https://sregistry.srv.cesga.es/api/container/mso4sc/test:latest
```

any magic migration to solve this?

Thanks in advance!

**Comment by vsoch** [comment]
I can't help much without knowing the error - you know the drill, you must look at the logs and determine what the server error actually was, then I can give some insight! And yes, you likely need to make migrations

```
python manage.py makemigrations
python manage.py migrate
```

**Comment by victorsndvg** [comment]
This is the error in the logs:

```
uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "./shub/apps/base/views/search.py", line 43, in search_query
uwsgi_1   |     return render(request, 'search/search_single_page.html', context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
uwsgi_1   |     content = loader.render_to_string(template_name, context, request, using=using)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
uwsgi_1   |     return template.render(context, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 68, in render
uwsgi_1   |     reraise(exc, self.backend)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 89, in reraise
uwsgi_1   |     six.reraise(exc.__class__, new, sys.exc_info()[2])
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
uwsgi_1   |     raise value.with_traceback(tb)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
uwsgi_1   |     return self.template.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 207, in render
uwsgi_1   |     return self._render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
uwsgi_1   |     return self.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 177, in render
uwsgi_1   |     return compiled_parent._render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
uwsgi_1   |     return self.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
uwsgi_1   |     result = block.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 72, in render
uwsgi_1   |     result = block.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 216, in render
uwsgi_1   |     return template.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 209, in render
uwsgi_1   |     return self._render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
uwsgi_1   |     return self.nodelist.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 990, in render
uwsgi_1   |     bit = node.render_annotated(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
uwsgi_1   |     return self.render(context)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 204, in render
uwsgi_1   |     template = context.template.engine.get_template(template_name)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/engine.py", line 162, in get_template
uwsgi_1   |     template, origin = self.find_template(template_name)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/template/engine.py", line 148, in find_template
uwsgi_1   |     raise TemplateDoesNotExist(name, tried=tried)
uwsgi_1   | django.template.exceptions.TemplateDoesNotExist: main/controls_scripts.html
```

**Comment by vsoch** [comment]
That's an easy one to fix! Since you weren't quick to respond here I'm going to open a new PR with fixes for your issue, stay tuned.

**Comment by victorsndvg** [comment]
Great thanks! :clap: :clap

**Comment by vsoch** [comment]
Please see https://github.com/singularityhub/sregistry/pull/129 and let's continue conversation there!

**Pull request merged**
