### PR TITLE
Support build-args option - Resolve #218

### LINKED ISSUE #218: Dockerfile with build-args
I'm developing an Ansible role (https://github.com/grycap/ansible-role-singularity-registry) to install sregistry by using your docker-compose recipes and sregistry. I want to automate the plugin's installation, so I need to uncomment some parts of the Dockerfile. I think that a good solution for avoiding search with regexp in the Dockerfile is using build-args to execute the desired RUN statements

### PR DESCRIPTION
**Pull request by serlophug**
By using this solution, it is possible to build vanessa/sregistry with the desired plugins requirements. For example, if we want to build with PAM and LDAP authentication, the build command is:
```bash
sudo docker build --build-arg ENABLE_LDAP=true --build-arg ENABLE_PAM=true -t vanessa/sregistry ${path_to_dockerfile}
````

### CODE REVIEW

**Comment by vsoch** [comment]
Beautiful work! When tests pass, we are good to go :) An seriously, what a great idea!

**Comment by serlophug** [comment]
I just completed the plugin documentation. Besides, I added a brief section to define how the plugin developers can modify the Dockerfile with the installation commands for their requirements.

**Comment by serlophug** [comment]
Thank you so much :)

**Comment by vsoch** [comment]
Just doing some tests for passing the boolean, here is my test file:

```
FROM busybox

ARG ENABLE_SAML=false
RUN if $ENABLE_SAML; then echo "SAML ENABLED" ; fi;
```
And confirm that when it's true, we see the echo:

```bash
$ docker build --build-arg ENABLE_SAML=true -t vanessa/test .
Sending build context to Docker daemon  5.632kB
Step 1/3 : FROM busybox
latest: Pulling from library/busybox
8e674ad76dce: Pull complete 
Digest: sha256:c94cf1b87ccb80f2e6414ef913c748b105060debda482058d2b8d0fce39f11b9
Status: Downloaded newer image for busybox:latest
 ---> e4db68de4ff2
Step 2/3 : ARG ENABLE_SAML=false
 ---> Running in a5740995bdfd
Removing intermediate container a5740995bdfd
 ---> e1898f1de249
Step 3/3 : RUN if $ENABLE_SAML; then echo "SAML ENABLED" ; fi;
 ---> Running in a42e8ed6c045
SAML ENABLED
Removing intermediate container a42e8ed6c045
 ---> ce828ce17b83
Successfully built ce828ce17b83
Successfully tagged vanessa/test:latest
```

And when we don't provide it, we don't see the echo.

```bash
$ docker build -t vanessa/test .
Sending build context to Docker daemon  5.632kB
Step 1/3 : FROM busybox
 ---> e4db68de4ff2
Step 2/3 : ARG ENABLE_SAML=false
 ---> Using cache
 ---> e1898f1de249
Step 3/3 : RUN if $ENABLE_SAML; then echo "SAML ENABLED" ; fi;
 ---> Running in 6cd05f42012f
Removing intermediate container 6cd05f42012f
 ---> a082da06f875
Successfully built a082da06f875
```

**Pull request merged**
