### PR TITLE
Small documentation fixes

### PR DESCRIPTION
**Pull request by SethosII**
Fix documentation errors mentioned in https://github.com/singularityhub/sregistry/issues/416#issuecomment-1485078104.

### CODE REVIEW

**Comment by vsoch** [comment]
The path to ldap.png is correct. If it's not showing up you could try adding site.baseurl or similar to get the full path, although then it won't render in the markdown.

**Comment by SethosII** [comment]
@vsoch For me it looks like this in Firefox/Chrome/Edge: 
ldap_image_broken

I use this way to include images in my Jekyll sites: `/sregistry/docs/plugins/ldap/ldap.png` but [other images in the repository](https://github.com/singularityhub/sregistry/search?p=4&q=png) use something like this for the paths: `../../assets/img/bitbucket-consumer.png`.

By the way, should the ldap image also be in `assets/img`?

**Comment by vsoch** [comment]
If that works for the other images, moving it there should be a good idea! 👍

**Comment by SethosII** [comment]
@vsoch I also changed it for the images of the globus page.

**Comment by vsoch** [comment]
Did you run locally to confirm they are all visible? That's the last check I'd do - once you confirm that we can merge I think!

**Comment by vsoch** [comment]
@SethosII I usually use jekyll from rb-env (and I haven't installed for a while) so I suspect the install might vary. If it was hard /annoying enough and you want to tweak the docs please feel free to open another PR, but it's not required!

**Pull request merged**
