### PR TITLE
Adding auth and push library endpoints

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add auth, and push endpoints for the library in Singularity Registry Server - the goal is to have a more robust push and one that doesn't require a custom client (issue #139). 

 - [x] verify turms 200 response if the token is valid, 404 otherwise 
 - [x] [status](https://github.com/sylabs/singularity/blob/b7713c775e61bd4dc3dab1b69dae1d2debcce91f/internal/app/singularity/remote_status.go) needs to be able to be run to populate these fields:
 - [x] collections listing (taking permissions into account)
 - [x] single collection and container retrieval (need to figure out how works when creating new one)

The PR also will handle large uploads, which currently poop out at 2GB.

## Issues Addressed

This PR will close:

 - #139  
 - #239 
 - #190
 - And adding a variable for Google Analytics
 
## How to Test

First clone the branch here (-b test/library-auth-push) into a new spot. 

```bash
git clone -b test/library-auth-push https://www.github.com/singularityhub/sregistry 
```

Stop and remove any previous containers on your host

```bash
docker-compose stop
docker-compose rm
```

### Rebuild

You'll need to rebuild the main and nginx containers, along with creating the most basic [secrets](https://singularityhub.github.io/sregistry/docs/install/settings) so you can login and run the containers. When you are ready, rebuild the containers:

```bash
docker build -t quay.io/vanessa/sregistry .
cd nginx
docker build -t quay.io/vanessa/sregistry_nginx .
```

When the PR changes are integrated, these will obviously be released and you wouldn't need to build on your own. The other files (nginx.conf) also have changes, but those will propogate when you restart containers.

### Custom Singularity
By default, the Singularity client simply won't honor a registry endpoint without https, and it shouldn't, because that would be passing secrets using a non secure connection. So in order to test with localhost, you'll need to edit [this file](https://github.com/sylabs/singularity/blob/5e483be4af2e120e646d33f0757e855c8d3be2da/internal/pkg/remote/remote.go#L237)
and re-compile Singularity to set the url to have http.

At this point you can follow the instructions in client.md below, including:
 - adding your registry as a remote
 - authenticating with your token
 - pushing away!

I'm also adding the same page rendered here:

[singularity-registry-client.pdf](https://github.com/singularityhub/sregistry/files/3720859/singularity-registry-client.pdf)

Testing locally, I've pushed a container that is 8GB. That is a MAJOR chonker
```bash
$ singularity push -U rustarok_latest.sif library://vsoch/dinosaur-collection/rustarok:latest
WARNING: Skipping container verifying
INFO:    http://127.0.0.1
INFO:    0a4cb168d3dabc3c21a15476be7f4a90396bc2c1
INFO:    library://vsoch/dinosaur-collection/rustarok:latest
INFO:    [latest]
 8.09 GiB / 8.09 GiB [====================================================================] 100.00% 91.31 MiB/s 1m30s
```
and I think we've not only added these endpoints (to not rely on the sregistry client, but have it for backup for older containers) but also fixed the upload size issue using those endpoints.

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Note that I still need to add the collection upload limit checks (just forgot to!) but that's a tiny detail.

**Comment by kamedodji** [comment]
It's a great new to make this working.
I just test it but got bellow error :
```
# singularity remote list
NAME          URI              GLOBAL
SylabsCloud   cloud.sylabs.io  YES
[localCloud]  192.168.56.111   NO

# singularity push -U stretch-base.img library://192.168.56.111/test/stretch:base
FATAL:   Unable to get library service URI: error response from server: 500

uwsgi_1      | Internal Server Error: /assets/config/config.prod.json
uwsgi_1      | Traceback (most recent call last):
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1      |     response = get_response(request)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1      |     response = self.process_exception_by_middleware(e, request)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/ratelimit/decorators.py", line 30, in _wrapped
uwsgi_1      |     return fn(*args, **kw)
uwsgi_1      |   File "./shub/apps/base/views/assets.py", line 22, in config_prod_json
uwsgi_1      |     return render(request, 'assets/config.prod.json')
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
uwsgi_1      |     content = loader.render_to_string(template_name, context, request, using=using)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
uwsgi_1      |     template = get_template(template_name, using=using)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 19, in get_template
uwsgi_1      |     raise TemplateDoesNotExist(template_name, chain=chain)
uwsgi_1      | django.template.exceptions.TemplateDoesNotExist: assets/config.prod.json
uwsgi_1      | [pid: 37|app: 0|req: 12/55] 192.168.56.111 () {32 vars in 437 bytes} [Sat Oct 26 10:08:17 2019] GET /assets/config/config.prod.json => generated 850 bytes in 2 msecs (HTTP/1.1 500) 3 headers in 128 bytes (1 switches on core 2)
```

In fact, i got same error on `singularity pull request...` :
```
singularity pull --library https://192.168.56.111 test/nginx:latest
```
Of course, i have created successfully `test` collection and uploaded `nginx` image...

Indeed can't figure out file `config.prod.json`

Thanks for your great jobs...

**Comment by vsoch** [comment]
Ack, totally my bad! Assets is on my gitignore (because the main assets folder in the root we would want to ignore) but because of that, I missed adding that template. And yes, pretty much nothing will work without it. I just added it: https://github.com/singularityhub/sregistry/pull/240/commits/28761410f16634c2238ef35058e54757ff5e72c2 so you should be able to pull again from the branch to get it, and then try again!

**Comment by kamedodji** [comment]
Thanks a lot for this quick fix!
But i still faced another issue:
```
singularity push -U stretch-base.img library://127.0.0.1/test/stretch:base
WARNING: Skipping container verifying
FATAL:   creation did not succeed: 0

docker-compose logs -f uwsgi
wsgi_1      | [pid: 39|app: 0|req: 10/25] 192.168.56.111 () {32 vars in 437 bytes} [Sat Oct 26 12:30:45 2019] GET /assets/config/config.prod.json => generated 488 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 109 bytes (1 switches on core 3)
uwsgi_1      | [pid: 37|app: 0|req: 9/26] 192.168.56.111 () {32 vars in 437 bytes} [Sat Oct 26 12:30:45 2019] GET /assets/config/config.prod.json => generated 488 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 109 bytes (1 switches on core 1)
uwsgi_1      | GET NamedEntityView
uwsgi_1      | <QueryDict: {}>
uwsgi_1      | 127.0.0.1
uwsgi_1      | Not Found: /v1/entities/127.0.0.1
uwsgi_1      | [pid: 40|app: 0|req: 3/27] 192.168.56.111 () {34 vars in 488 bytes} [Sat Oct 26 12:30:46 2019] GET /v1/entities/127.0.0.1 => generated 0 bytes in 7 msecs (HTTP/1.1 404) 4 headers in 115 bytes (1 switches on core 3)
uwsgi_1      | Method Not Allowed: /v1/entities
uwsgi_1      | [pid: 38|app: 0|req: 6/28] 192.168.56.111 () {38 vars in 551 bytes} [Sat Oct 26 12:30:46 2019] POST /v1/entities => generated 41 bytes in 1 msecs (HTTP/1.1 405) 5 headers in 157 bytes (1 switches on core 2)
```

And neither pull doesn't work too: 
```
 # singularity pull library://192.168.56.111 test/nginx:latest
FATAL:   While getting image info: error decoding image: invalid ObjectId in JSON: "1"
```

Any way to have more verbose log ?

**Comment by vsoch** [comment]
Are you using a Singularity compiles to allow for http and not https? See the description  - I had to do this to develop locally

**Comment by vsoch** [comment]
Also if you’ve set the library to already be 127.0.0.1 I don’t think you should include it in the uri again.  The error messages show that you’re trying to find a container collection with the base name of the registry which is incorrect.

**Comment by vsoch** [comment]
Please look at the description and follow all of the instructions – note that the example that I gave to push does not include the registry URI.

**Comment by kamedodji** [comment]
No, i configured a self-signed ssl certificate and setup https access...
Let me follow your latest feedback.

**Comment by vsoch** [comment]
Ah, that works too! You shouldn't need to recompile Singularity then, as long as https://127.0.0.1 is good (and set as the remote endpoint).

**Comment by kamedodji** [comment]
I found and fixed my issue : you must use `singularity 3.3.0+` 
May be it's can be relevant to mention it in documentation [singularity-registry-client.pdf](https://github.com/singularityhub/sregistry/files/3720859/singularity-registry-client.pdf) ?
Thanks again for this great job...

**Comment by vsoch** [comment]
Oh yes of course! Just added https://github.com/singularityhub/sregistry/pull/240/commits/5c0b9d9fc8fc7cbb2be616db451c551ef728cdfb (and that renders the original PDF I shared). Did you have any other issues?

**Comment by vsoch** [comment]
And why did you end with a dot dot dot? Are you being sarcastic?

**Comment by kamedodji** [comment]
No, excuse! I'm a real fan ;-) ! It's work very fine.
For your information, i'm working to convince colleagues of biggest energy society at France to adopt `sregistry`! I'll let you known.
We want to provide a `builder` service to our HPC users probably with `sregistry + jenkins`
I'm also working to [Native Port](https://github.com/singularityhub/sregistry/issues/124). And probaly i'll let you soon.

**Comment by vsoch** [comment]
Awesome! This is a little old now, but a center in Colorado did something similar to provide containers for their cluster -> dl.acm.org/citation.cfm?id=3219147. If you provide it as a builder (and then registry) service, make sure that you are using a version of Singularity that caches an image from an `shub`, at least if your registry is serving from the local filesystem. If you aren't able to cache container requests and are using a filesystem that can handle the load, then you might want to try a deployment that could handle all those requests in parallel. If you are using a filesystem that can't, then likely you'd want to be able to push to some cloud storage and then deliver with a signed URL. This is actually implemented for the google build plugin, but that also uses Google Cloud Build, so what we would need to do is have Singularity Registry Server return a signed URL to allow for uploading to your cloud provider of choice, and then the same for download.

Anyhoo, one thing at a time! Keep me updated for sure, whatever isn't currently implemented definitely can be - I'm doing it on a request basis.

**Comment by kamedodji** [comment]
Thanks for this feedback. I really appreciate. Many inputs, but i need to read it back carefully to understand everything ;-) !
Till now, I'm watching dl.acm.org/citation.cfm?id=3219147.  Really interesting.

Last question : do you plan to also support `singularity pull --remote` ?

**Comment by vsoch** [comment]
What does that do?

**Comment by kamedodji** [comment]
excuse, i mean : `singularity build --remote`

**Comment by vsoch** [comment]
I added support to use [Google Cloud Build as a plugin](https://singularityhub.github.io/sregistry/docs/plugins/google-build), which is essentially that.

**Pull request merged**
